"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { ArrowLeft, Check, MapPin, Star } from "lucide-react"
import UserMenu from "@/components/user-menu"

const professionals = [
  { name: "Martín Sosa", category: "Electricista", photo: "https://i.pravatar.cc/160?img=12", distance: "0,8 km", rating: 4.9 },
  { name: "Diego Acosta", category: "Electricista", photo: "https://i.pravatar.cc/160?img=11", distance: "1,4 km", rating: 4.8 },
  { name: "Lucía Benítez", category: "Electricista", photo: "https://i.pravatar.cc/160?img=47", distance: "2,1 km", rating: 4.7 },
]

export default function CrearSolicitudPage() {
  const router = useRouter()
  const [step, setStep] = useState(1)
  const [location, setLocation] = useState("")
  const [category, setCategory] = useState("")
  const [day, setDay] = useState("")
  const [time, setTime] = useState("")
  const [professional, setProfessional] = useState("")
  const [sort, setSort] = useState<"distance" | "rating">("distance")
  const [sent, setSent] = useState(false)
  const orderedProfessionals = useMemo(() => [...professionals].sort((a, b) => sort === "distance" ? Number.parseFloat(a.distance) - Number.parseFloat(b.distance) : b.rating - a.rating), [sort])
  const canContinue = step === 1 ? Boolean(location) : step === 2 ? Boolean(category) : step === 3 ? Boolean(day && time) : Boolean(professional)

  if (sent) return <main className="min-h-screen bg-[var(--paper)] px-4 py-10 text-[var(--ink)]"><div className="mx-auto max-w-xl rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center"><Check className="mx-auto text-emerald-600" size={34}/><h1 className="mt-4 font-serif text-3xl">Solicitud enviada</h1><p className="mt-2 text-sm text-emerald-800">Tu solicitud fue enviada a {professional}.</p><Link href="/mis-solicitudes" className="mt-6 inline-flex rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-bold text-white">Volver a mis solicitudes</Link></div></main>

  return <main className="min-h-screen overflow-x-hidden bg-[var(--paper)] text-[var(--ink)]"><header className="border-b border-[var(--line)] bg-[var(--paper)]"><div className="mx-auto flex max-w-[1240px] items-center justify-between gap-3 px-6 py-5 lg:px-10"><Link href="/mis-solicitudes" className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-[10px] bg-[var(--coral)] font-serif text-xl text-white">V</span><span className="font-serif text-xl">Vincula-UP</span></Link><UserMenu name="Sofía Martínez" role="Cliente" profileHref="/mis-solicitudes" /></div></header><section className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:py-12"><Link href="/mis-solicitudes" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--muted)] hover:text-[var(--ink)]"><ArrowLeft size={15}/>Volver al listado</Link><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--coral)]">Nueva solicitud</p><h1 className="mt-2 font-serif text-3xl sm:text-4xl">Encontrá el profesional indicado</h1><div className="mt-8 rounded-2xl border border-[var(--line)] bg-white p-4 shadow-sm sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Paso {step} de 4</p><h2 className="mt-1 font-serif text-2xl">{step === 1 ? "¿Dónde necesitás el servicio?" : step === 2 ? "¿Qué necesitás resolver?" : step === 3 ? "¿Cuándo te viene bien?" : "Elegí un profesional"}</h2></div><Link href="/mis-solicitudes" className="text-sm text-[var(--muted)]">Cancelar</Link></div>
{step === 1 && <div className="space-y-4">{location && <div className="relative overflow-hidden rounded-xl border border-[var(--line)] bg-[#e9eee8] p-4"><div className="h-40 rounded-lg border border-dashed border-[#9aa99a] bg-[linear-gradient(135deg,#dce7df_25%,transparent_25%),linear-gradient(45deg,#dce7df_25%,transparent_25%),linear-gradient(135deg,transparent_75%,#dce7df_75%),linear-gradient(45deg,transparent_75%,#dce7df_75%)] bg-[length:42px_42px] bg-[position:0_0,21px_0,21px_-21px,0_21px]"><div className="flex h-full items-center justify-center"><div className="rounded-full bg-[var(--coral)] p-3 text-white shadow-lg"><MapPin size={24}/></div></div></div><p className="mt-3 text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Ubicación seleccionada · Concepción del Uruguay</p></div>}<label htmlFor="service-address" className="block text-sm font-bold">Escribí la dirección del servicio<input id="service-address" name="serviceAddress" type="text" autoComplete="street-address" value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Ej. San Martín 1280, Concepción del Uruguay" className="mt-2 w-full rounded-xl border border-[var(--line)] px-4 py-3 text-sm font-normal outline-none focus:border-[var(--coral)]" /></label><button type="button" onClick={() => setLocation("25 de Mayo 742, Concepción del Uruguay")} className={`flex w-full items-start gap-3 rounded-xl border p-4 text-left ${location ? "border-[var(--coral)] bg-orange-50" : "border-[var(--line)]"}`}><MapPin className="mt-0.5 shrink-0 text-[var(--coral)]" size={20}/><span><b>Usar mi ubicación</b><span className="mt-1 block text-sm text-[var(--muted)]">Usar mi ubicación actual</span></span></button></div>}
{step === 2 && <div className="grid gap-3 sm:grid-cols-2">{["Electricidad domiciliaria", "Plomería y gas", "Pintura", "Carpintería"].map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-xl border p-4 text-left text-sm font-bold ${category === item ? "border-[var(--coral)] bg-orange-50" : "border-[var(--line)]"}`}>{item}</button>)}</div>}
{step === 3 && <div className="space-y-5"><div><p className="mb-3 text-sm font-bold">Día</p><div className="grid grid-cols-3 gap-2 sm:grid-cols-7">{["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"].map(item => <button key={item} onClick={() => setDay(item)} className={`h-11 rounded-lg border text-sm font-bold ${day === item ? "border-[var(--coral)] bg-[var(--coral)] text-white" : "border-[var(--line)]"}`}>{item}</button>)}</div></div><label className="block text-sm font-bold">Horario<select value={time} onChange={e => setTime(e.target.value)} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-white px-4 py-3 font-normal"><option value="">Elegí un horario</option><option>08:00 a 12:00 hs</option><option>12:00 a 16:00 hs</option><option>16:00 a 20:00 hs</option></select></label></div>}
{step === 4 && <div><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-[var(--muted)]">Profesionales disponibles para ese día y horario.</p><div className="flex gap-2 self-start"><button onClick={() => setSort("distance")} className={`rounded-full border px-3 py-2 text-xs font-bold ${sort === "distance" ? "border-[var(--coral)] bg-orange-50 text-[var(--coral)]" : "border-[var(--line)]"}`}>Proximidad</button><button onClick={() => setSort("rating")} className={`rounded-full border px-3 py-2 text-xs font-bold ${sort === "rating" ? "border-[var(--coral)] bg-orange-50 text-[var(--coral)]" : "border-[var(--line)]"}`}>Reputación</button></div></div><div className="grid gap-3">{orderedProfessionals.map(item => <button key={item.name} onClick={() => setProfessional(item.name)} className={`flex w-full min-w-0 items-center gap-3 rounded-xl border p-3 text-left ${professional === item.name ? "border-[var(--coral)] bg-orange-50" : "border-[var(--line)]"}`}><img src={item.photo} alt={`Foto de ${item.name}`} className="h-14 w-14 shrink-0 rounded-full object-cover"/><span className="min-w-0 flex-1"><b className="block truncate">{item.name}</b><span className="block text-xs text-[var(--muted)]">{item.category} · {item.distance}</span><span className="mt-1 flex items-center gap-1 text-xs font-bold"><Star size={13} className="fill-amber-400 text-amber-400"/>{item.rating}</span></span><span className="shrink-0 text-xs font-bold text-[var(--coral)]">{professional === item.name ? "Elegido" : "Elegir"}</span></button>)}</div></div>}
<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button type="button" disabled={step === 1} onClick={() => setStep(Math.max(1, step - 1))} className="inline-flex items-center justify-center gap-2 rounded-full border border-[var(--line)] px-5 py-3 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40"><ArrowLeft size={16}/>Atrás</button>{step < 4 ? <button disabled={!canContinue} onClick={() => setStep(step + 1)} className="rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Continuar</button> : <button disabled={!canContinue} onClick={() => router.push(`/mis-solicitudes?created=1&professional=${encodeURIComponent(professional)}&category=${encodeURIComponent(category)}&address=${encodeURIComponent(location)}&day=${encodeURIComponent(day)}&time=${encodeURIComponent(time)}`)} className="rounded-full bg-[var(--coral)] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Enviar solicitud</button>}</div></div></section></main>
}
