spring.application.name=ms-usuarios
server.port=${PORT:8081}

spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:usuarios;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
