events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;

  # Buffer grande para headers de Keycloak
  proxy_buffer_size   128k;
  proxy_buffers       4 256k;
  proxy_busy_buffers_size 256k;

  server {
    listen 80;
    server_name localhost vincula-up.local 127.0.0.1;

    # Redirigir todo el tráfico HTTP → HTTPS
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name localhost vincula-up.local 127.0.0.1;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      proxy_pass http://bff-web:9001;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
    }

    # Keycloak: realms, resources, js y login-actions
    location /realms/ {
      proxy_pass http://keycloak:8080/realms/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port 443;
    }

    location /resources/ {
      proxy_pass http://keycloak:8080/resources/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port 443;
    }

    location /js/ {
      proxy_pass http://keycloak:8080/js/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port 443;
    }
  }
}
